puts "PAÍSES >>>"

Country.find_or_create_by(name:'AFEGANISTAO').update(acronym:'AF', country:'AFGHANISTAN')
Country.find_or_create_by(name:'AFRICA DO SUL').update(acronym:'ZA', country:'SOUTH AFRICA')
Country.find_or_create_by(name:'ALBANIA').update(acronym:'AL', country:'ALBANIA')
Country.find_or_create_by(name:'ALEMANHA').update(acronym:'DE', country:'GERMANY')
Country.find_or_create_by(name:'ANDORRA').update(acronym:'AD', country:'ANDORRA')
Country.find_or_create_by(name:'ANGOLA').update(acronym:'AO', country:'ANGOLA')
Country.find_or_create_by(name:'ANTIGUA E BARBUDA').update(acronym:'AG', country:'ANTIGUA AND BARBUDA')
Country.find_or_create_by(name:'ARABIA SAUDITA').update(acronym:'SA', country:'SAUDI ARABIA')
Country.find_or_create_by(name:'ARGELIA').update(acronym:'DZ', country:'ALGERIA')
Country.find_or_create_by(name:'ARGENTINA').update(acronym:'AR', country:'ARGENTINA')
Country.find_or_create_by(name:'ARMENIA').update(acronym:'AM', country:'ARMENIA')
Country.find_or_create_by(name:'AUSTRALIA').update(acronym:'AU', country:'AUSTRALIA')
Country.find_or_create_by(name:'AUSTRIA').update(acronym:'AT', country:'AUSTRIA')
Country.find_or_create_by(name:'AZERBAIJAO').update(acronym:'AZ', country:'AZERBAIJAN')
Country.find_or_create_by(name:'BAHAMAS').update(acronym:'BS', country:'BAHAMAS')
Country.find_or_create_by(name:'BAHREIN').update(acronym:'BH', country:'BAHRAIN')
Country.find_or_create_by(name:'BANGLADESH').update(acronym:'BD', country:'BANGLADESH')
Country.find_or_create_by(name:'BARBADOS').update(acronym:'BB', country:'BARBADOS')
Country.find_or_create_by(name:'BELARUS').update(acronym:'BY', country:'BELARUS')
Country.find_or_create_by(name:'BELGICA').update(acronym:'BE', country:'BELGIUM')
Country.find_or_create_by(name:'BELIZE').update(acronym:'BZ', country:'BELIZE')
Country.find_or_create_by(name:'BENIN').update(acronym:'BJ', country:'BENIN')
Country.find_or_create_by(name:'BOLIVIA').update(acronym:'BO', country:'BOLIVIA')
Country.find_or_create_by(name:'BOSNIA').update(acronym:'BA', country:'BOSNIA')
Country.find_or_create_by(name:'BOTSWANA').update(acronym:'BW', country:'BOTSWANA')
Country.find_or_create_by(name:'BRASIL').update(acronym:'BR', country:'BRAZIL')
Country.find_or_create_by(name:'BRUNEI').update(acronym:'BN', country:'BRUNEI DARUSSALAM')
Country.find_or_create_by(name:'BULGARIA').update(acronym:'BG', country:'BULGARIA')
Country.find_or_create_by(name:'BURKINA FASO').update(acronym:'BF', country:'BURKINA FASO')
Country.find_or_create_by(name:'BURUNDI').update(acronym:'BI', country:'BURUNDI')
Country.find_or_create_by(name:'BUTAO').update(acronym:'BT', country:'BHUTAN')
Country.find_or_create_by(name:'CABO VERDE').update(acronym:'CV', country:'CABO VERDE')
Country.find_or_create_by(name:'CAMAROES').update(acronym:'CM', country:'CAMEROON')
Country.find_or_create_by(name:'CAMBOJA').update(acronym:'KH', country:'CAMBODIA')
Country.find_or_create_by(name:'CANADA').update(acronym:'CA', country:'CANADA')
Country.find_or_create_by(name:'CATAR').update(acronym:'QA', country:'QATAR')
Country.find_or_create_by(name:'CHADE').update(acronym:'TD', country:'CHAD')
Country.find_or_create_by(name:'CHILE').update(acronym:'CL', country:'CHILE')
Country.find_or_create_by(name:'CHINA').update(acronym:'CN', country:'CHINA')
Country.find_or_create_by(name:'CHIPRE').update(acronym:'CY', country:'CYPRUS')
Country.find_or_create_by(name:'COLOMBIA').update(acronym:'CO', country:'COLOMBIA')
Country.find_or_create_by(name:'COMORES').update(acronym:'KM', country:'COMOROS')
Country.find_or_create_by(name:'CONGO, REPUBLICA DEMOCRATICA DO').update(acronym:'CG', country:'CONGO')
Country.find_or_create_by(name:'CONGO, REPUBLICA DO').update(acronym:'CG', country:'CONGO')
Country.find_or_create_by(name:'COOK, ILHAS').update(acronym:'CK', country:'COOK, ISLANDS')
Country.find_or_create_by(name:'COREIA DO NORTE').update(acronym:'KP', country:'KOREA')
Country.find_or_create_by(name:'COREIA DO SUL').update(acronym:'KR', country:'KOREA, REPUBLIC OF')
Country.find_or_create_by(name:'COSTA DO MARFIM').update(acronym:'CI', country:'CÔTE DIVOIRE')
Country.find_or_create_by(name:'COSTA RICA').update(acronym:'CR', country:'COSTA RICA')
Country.find_or_create_by(name:'CROACIA').update(acronym:'HR', country:'CROATIA')
Country.find_or_create_by(name:'CUBA').update(acronym:'CU', country:'CUBA')
Country.find_or_create_by(name:'DINAMARCA').update(acronym:'DK', country:'DENMARK')
Country.find_or_create_by(name:'DJIBOUTI').update(acronym:'DJ', country:'DJIBOUTI')
Country.find_or_create_by(name:'DOMINICA').update(acronym:'DM', country:'DOMINICA')
Country.find_or_create_by(name:'EGITO').update(acronym:'EG', country:'EGYPT')
Country.find_or_create_by(name:'EL SALVADOR').update(acronym:'SV', country:'EL SALVADOR')
Country.find_or_create_by(name:'EMIRADOS ARABES').update(acronym:'AE', country:'UNITED ARAB EMIRATES')
Country.find_or_create_by(name:'EQUADOR').update(acronym:'EC', country:'ECUADOR')
Country.find_or_create_by(name:'ERITREIA').update(acronym:'ER', country:'ERITREA')
Country.find_or_create_by(name:'ESLOVAQUIA').update(acronym:'SK', country:'SLOVAKIA')
Country.find_or_create_by(name:'ESLOVENIA').update(acronym:'SI', country:'SLOVENIA')
Country.find_or_create_by(name:'ESPANHA').update(acronym:'ES', country:'SPAIN')
Country.find_or_create_by(name:'ESTADOS UNIDOS DA AMÉRICA').update(acronym:'US', country:'UNITED STATES OF AMERICA')
Country.find_or_create_by(name:'ESTONIA').update(acronym:'EE', country:'ESTONIA')
Country.find_or_create_by(name:'ETIOPIA').update(acronym:'ET', country:'ETHIOPIA')
Country.find_or_create_by(name:'FIJI, ILHAS').update(acronym:'FJ', country:'FIJI')
Country.find_or_create_by(name:'FILIPINAS').update(acronym:'PH', country:'PHILIPPINES')
Country.find_or_create_by(name:'FINLANDIA').update(acronym:'FI', country:'FINLAND')
Country.find_or_create_by(name:'FRANCA').update(acronym:'FR', country:'FRANCE')
Country.find_or_create_by(name:'GABAO').update(acronym:'GA', country:'GABON')
Country.find_or_create_by(name:'GAMBIA').update(acronym:'GM', country:'GAMBIA')
Country.find_or_create_by(name:'GANA').update(acronym:'GH', country:'GHANA')
Country.find_or_create_by(name:'GEORGIA').update(acronym:'GE', country:'GEORGIA')
Country.find_or_create_by(name:'GRANADA').update(acronym:'GD', country:'GRENADA')
Country.find_or_create_by(name:'GRECIA').update(acronym:'GR', country:'GREECE')
Country.find_or_create_by(name:'GUATEMALA').update(acronym:'GT', country:'GUATEMALA')
Country.find_or_create_by(name:'GUIANA').update(acronym:'GY', country:'GUYANA')
Country.find_or_create_by(name:'GUIANA FRANCESA').update(acronym:'GF', country:'FRENCH GUIANA')
Country.find_or_create_by(name:'GUINE').update(acronym:'GN', country:'GUINEA')
Country.find_or_create_by(name:'GUINE EQUATORIAL').update(acronym:'GQ', country:'EQUATORIAL GUINEA')
Country.find_or_create_by(name:'GUINE-BISSAU').update(acronym:'GW', country:'GUINEA-BISSAU')
Country.find_or_create_by(name:'HAITI').update(acronym:'HT', country:'HAITI')
Country.find_or_create_by(name:'HONDURAS').update(acronym:'HN', country:'HONDURAS')
Country.find_or_create_by(name:'HONG KONG').update(acronym:'HK', country:'HONG KONG')
Country.find_or_create_by(name:'HUNGRIA').update(acronym:'HU', country:'HUNGARY')
Country.find_or_create_by(name:'IEMEN').update(acronym:'YE', country:'YEMEN')
Country.find_or_create_by(name:'INDIA').update(acronym:'IN', country:'INDIA')
Country.find_or_create_by(name:'INDONESIA').update(acronym:'ID', country:'INDONESIA')
Country.find_or_create_by(name:'IRAQUE').update(acronym:'IQ', country:'IRAQ')
Country.find_or_create_by(name:'IRLANDA').update(acronym:'IE', country:'IRELAND')
Country.find_or_create_by(name:'ISLANDIA').update(acronym:'IS', country:'ICELAND')
Country.find_or_create_by(name:'ISRAEL').update(acronym:'IL', country:'ISRAEL')
Country.find_or_create_by(name:'ITALIA').update(acronym:'IT', country:'ITALY')
Country.find_or_create_by(name:'JAMAICA').update(acronym:'JM', country:'JAMAICA')
Country.find_or_create_by(name:'JAPAO').update(acronym:'JP', country:'JAPAN')
Country.find_or_create_by(name:'JORDANIA').update(acronym:'JO', country:'JORDAN')
Country.find_or_create_by(name:'KIRIBATI').update(acronym:'KI', country:'KIRIBATI')
Country.find_or_create_by(name:'KOSOVO').update(acronym:'XK ', country:'KOSOVO')
Country.find_or_create_by(name:'KUWAIT').update(acronym:'KW', country:'KUWAIT')
Country.find_or_create_by(name:'LAOS').update(acronym:'LA', country:'LAOS')
Country.find_or_create_by(name:'LESOTO').update(acronym:'LS', country:'LESOTHO')
Country.find_or_create_by(name:'LETONIA').update(acronym:'LV', country:'LETONIA')
Country.find_or_create_by(name:'LIBANO').update(acronym:'LB', country:'LIBAN')
Country.find_or_create_by(name:'LIBERIA').update(acronym:'LR', country:'LIBERIA')
Country.find_or_create_by(name:'LIBIA').update(acronym:'LY', country:'LIBYA')
Country.find_or_create_by(name:'LIECHTENSTEIN').update(acronym:'LI', country:'LIECHTENSTEIN')
Country.find_or_create_by(name:'LITUANIA').update(acronym:'LT', country:'LITHUANIA')
Country.find_or_create_by(name:'LUXEMBURGO').update(acronym:'LU', country:'LUXEMBOURG')
Country.find_or_create_by(name:'MACAU').update(acronym:'MO', country:'MACAO')
Country.find_or_create_by(name:'MACEDONIA').update(acronym:'MK', country:'NORTH MACEDONIA')
Country.find_or_create_by(name:'MADAGASCAR').update(acronym:'MG', country:'MADAGASCAR')
Country.find_or_create_by(name:'MALASIA').update(acronym:'MY', country:'MALAYSIA')
Country.find_or_create_by(name:'MALAWI').update(acronym:'MW', country:'MALAWI')
Country.find_or_create_by(name:'MALDIVAS').update(acronym:'MV', country:'MALDIVES')
Country.find_or_create_by(name:'MALI').update(acronym:'ML', country:'MALI')
Country.find_or_create_by(name:'MALTA').update(acronym:'MT', country:'MALTA')
Country.find_or_create_by(name:'MARIANAS, ILHAS').update(acronym:'MP', country:'NORTHERN MARIANA ISLANDS')
Country.find_or_create_by(name:'MARROCOS').update(acronym:'MA', country:'MOROCCO')
Country.find_or_create_by(name:'MARSHALL, ILHAS').update(acronym:'MH', country:'MARSHALL ISLANDS')
Country.find_or_create_by(name:'MAURICIO').update(acronym:'', country:'')
Country.find_or_create_by(name:'MAURITANIA').update(acronym:'MR', country:'MAURITANIA')
Country.find_or_create_by(name:'MEXICO').update(acronym:'MX', country:'MEXICO')
Country.find_or_create_by(name:'MICRONESIA').update(acronym:'FM', country:'MICRONESIA (FEDERATED STATES OF)')
Country.find_or_create_by(name:'MOCAMBIQUE').update(acronym:'MZ', country:'MOZAMBIQUE')
Country.find_or_create_by(name:'MOLDOVA').update(acronym:'MD', country:'MOLDOVA, REPUBLIC OF')
Country.find_or_create_by(name:'MONACO').update(acronym:'MC', country:'MONACO')
Country.find_or_create_by(name:'MONGOLIA').update(acronym:'MN', country:'MONGOLIA')
Country.find_or_create_by(name:'MONTENEGRO').update(acronym:'ME', country:'MONTENEGRO')
Country.find_or_create_by(name:'MYANMAR').update(acronym:'MM', country:'MYANMAR')
Country.find_or_create_by(name:'NAMIBIA').update(acronym:'NA', country:'NAMIBIA')
Country.find_or_create_by(name:'NAURU').update(acronym:'NR', country:'NAURU')
Country.find_or_create_by(name:'NEPAL').update(acronym:'NP', country:'NEPAL')
Country.find_or_create_by(name:'NICARAGUA').update(acronym:'NI', country:'NICARAGUA')
Country.find_or_create_by(name:'NIGER').update(acronym:'NE', country:'NIGER')
Country.find_or_create_by(name:'NIGERIA').update(acronym:'NG', country:'NIGERIA')
Country.find_or_create_by(name:'NORUEGA').update(acronym:'NO', country:'NORWAY')
Country.find_or_create_by(name:'NOVA ZELANDIA').update(acronym:'NZ', country:'NEW ZEALAND')
Country.find_or_create_by(name:'ORDEM SOBERANA E MILITAR DE MALTA').update(acronym:'MT', country:'MALTA')
Country.find_or_create_by(name:'CountryES BAIXOS').update(acronym:'NL', country:'NETHERLANDS, KINGDOM OF THE')
Country.find_or_create_by(name:'PALAU').update(acronym:'PW', country:'PALAU')
Country.find_or_create_by(name:'PALESTINA').update(acronym:'PS', country:'PALESTINE, STATE OF')
Country.find_or_create_by(name:'PANAMA').update(acronym:'PA', country:'PANAMA')
Country.find_or_create_by(name:'PAPUA NOVA GUINE').update(acronym:'PG', country:'PAPUA NEW GUINEA')
Country.find_or_create_by(name:'PAQUISTAO').update(acronym:'PK', country:'PAKISTAN')
Country.find_or_create_by(name:'PARAGUAI').update(acronym:'PY', country:'PARAGUAY')
Country.find_or_create_by(name:'PERU').update(acronym:'PE', country:'PERU')
Country.find_or_create_by(name:'POLONIA').update(acronym:'PL', country:'POLAND')
Country.find_or_create_by(name:'PORTUGAL').update(acronym:'PT', country:'PORTUGAL')
Country.find_or_create_by(name:'QUENIA').update(acronym:'KE', country:'KENYA')
Country.find_or_create_by(name:'QUIRGUISTAO').update(acronym:'KG', country:'KYRGYZSTAN')
Country.find_or_create_by(name:'REINO UNIDO').update(acronym:'GB', country:'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND')
Country.find_or_create_by(name:'REPUBLICA CENTRO AFRICANA').update(acronym:'CF', country:'CENTRAL AFRICAN REPUBLIC')
Country.find_or_create_by(name:'REPUBLICA DOMINICANA').update(acronym:'DO', country:'DOMINICAN REPUBLIC')
Country.find_or_create_by(name:'REPUBLICA TCHECA').update(acronym:'CZ', country:'CZECHIA')
Country.find_or_create_by(name:'ROMENIA').update(acronym:'RO', country:'ROMANIA')
Country.find_or_create_by(name:'RUANDA').update(acronym:'RW', country:'RWANDA')
Country.find_or_create_by(name:'RUSSIA').update(acronym:'RU', country:'RUSSIAN FEDERATION')
Country.find_or_create_by(name:'SALOMÃO, ILHAS').update(acronym:'SB', country:'SOLOMON ISLANDS')
Country.find_or_create_by(name:'SAMOA OCIDENTAL').update(acronym:'WS', country:'SAMOA')
Country.find_or_create_by(name:'SAN MARINO').update(acronym:'SM', country:'SAN MARINO')
Country.find_or_create_by(name:'SANTA LUCIA').update(acronym:'LC', country:'SAINT LUCIA')
Country.find_or_create_by(name:'SAO CRISTOVAO E NEVIS').update(acronym:'KN', country:'SAINT KITTS AND NEVIS')
Country.find_or_create_by(name:'SAO TOME E PRINCIPE').update(acronym:'', country:'')
Country.find_or_create_by(name:'SAO VICENTE E GRANADINAS').update(acronym:'VC', country:'SAINT VINCENT AND THE GRENADINES')
Country.find_or_create_by(name:'SEICHELES').update(acronym:'SC', country:'SEYCHELLES')
Country.find_or_create_by(name:'SENEGAL').update(acronym:'SN', country:'SENEGAL')
Country.find_or_create_by(name:'SERRA LEOA').update(acronym:'SL', country:'SIERRA LEONE')
Country.find_or_create_by(name:'SERVIA').update(acronym:'RS', country:'SERBIA')
Country.find_or_create_by(name:'SINGAPURA').update(acronym:'SG', country:'SINGAPORE')
Country.find_or_create_by(name:'SIRIA').update(acronym:'SY', country:'SYRIAN ARAB REPUBLIC')
Country.find_or_create_by(name:'SOMALIA').update(acronym:'SO', country:'SOMALIA')
Country.find_or_create_by(name:'SRI LANKA').update(acronym:'LK', country:'SRI LANKA')
Country.find_or_create_by(name:'SUAZILANDIA').update(acronym:'', country:'')
Country.find_or_create_by(name:'SUDAO').update(acronym:'SD', country:'SUDAN')
Country.find_or_create_by(name:'SUDAO DO SUL').update(acronym:'SD', country:'SUDAN')
Country.find_or_create_by(name:'SUECIA').update(acronym:'SE', country:'SWEDEN')
Country.find_or_create_by(name:'SUICA').update(acronym:'CH', country:'SWITZERLAND')
Country.find_or_create_by(name:'SURINAME').update(acronym:'SR', country:'SURINAME')
Country.find_or_create_by(name:'TAILANDIA').update(acronym:'TH', country:'THAILAND')
Country.find_or_create_by(name:'TAIWAN').update(acronym:'TW', country:'TAIWAN')
Country.find_or_create_by(name:'TANZANIA').update(acronym:'TZ', country:'TANZANIA, UNITED REPUBLIC OF')
Country.find_or_create_by(name:'TIMOR-LESTE').update(acronym:'TL', country:'TIMOR-LESTE')
Country.find_or_create_by(name:'TOGO').update(acronym:'TG', country:'TOGO')
Country.find_or_create_by(name:'TONGA').update(acronym:'TO', country:'TONGA')
Country.find_or_create_by(name:'TRINIDAD E TOBAGO').update(acronym:'TT', country:'TRINIDAD AND TOBAGO')
Country.find_or_create_by(name:'TUNISIA').update(acronym:'TN', country:'TUNISIA')
Country.find_or_create_by(name:'TURCOMENISTAO').update(acronym:'TM', country:'TURKMENISTAN')
Country.find_or_create_by(name:'TURQUIA').update(acronym:'TR', country:'TÜRKIYE')
Country.find_or_create_by(name:'TUVALU').update(acronym:'TV', country:'TUVALU')
Country.find_or_create_by(name:'UCRANIA').update(acronym:'UA', country:'UKRAINE')
Country.find_or_create_by(name:'UGANDA').update(acronym:'UG', country:'UGANDA')
Country.find_or_create_by(name:'URUGUAI').update(acronym:'UY', country:'URUGUAY')
Country.find_or_create_by(name:'UZBEQUISTAO').update(acronym:'UZ', country:'UZBEKISTAN')
Country.find_or_create_by(name:'VANUATU').update(acronym:'VU', country:'VANUATU')
Country.find_or_create_by(name:'VATICANO').update(acronym:'VA', country:'VATICAN')
Country.find_or_create_by(name:'VENEZUELA').update(acronym:'VE', country:'VENEZUELA (BOLIVARIAN REPUBLIC OF)')
Country.find_or_create_by(name:'VIETNA').update(acronym:'VN ', country:'VIETNAM')
Country.find_or_create_by(name:'ZAMBIA').update(acronym:'ZM', country:'ZAMBIA')
Country.find_or_create_by(name:'ZIMBABUE').update(acronym:'ZW', country:'ZIMBABWE')
